CREATE TABLE EMPREGADO(
    IDEMPREGADO     BIGINT AUTO_INCREMENT,
    NMEMPREGADO     VARCHAR(100),
    DTNASCIMENTO    DATE,
    DTCONTRATACAO   DATE,
    NMLOGRADOURO    VARCHAR(100),
    NUENDERECO      VARCHAR(20),
    COMPLEMENTO     VARCHAR(100),
    BAIRRO          VARCHAR(150),
    CIDADE          VARCHAR(150),
    ESTADO          VARCHAR(2),
CONSTRAINT PK_EMPREGADO PRIMARY KEY(IDEMPREGADO));
